ani1 = str(input("\nAnimal: "))
vb1 = str(input("\nPresent-Tense Verb: "))
col1 = str(input("\nColor: "))
vb2 = str(input("\nAnother Present-Tense Verb: "))
ani2 = str(input("\nAnother Animal: "))
loc1 = str(input("\nPlace/Location: "))
adv1 = str(input("\nAdverb ending in 'ly': "))
emot1 = str(input("\nPrimary Emotion: "))
print("There once was a/an %s who loved to %s anything the color %s. One day, the %s decided to %s a/an %s it saw walking near %s. Before the %s could do that, however, the %s %s ran away, making the %s become very %s. THE END." % ani1, % vb1, %col1, %ani1, %vb2, %ani2, %loc1, %ani1, %ani2, %adv1, %ani1, %emot1)
