ani1 = input("\nAnimal: ")
vb1 = input("\nPresent-Tense Verb: ")
col1 = input("\nColor: ")
vb2 = input("\nAnother Present-Tense Verb: ")
ani2 = input("\nAnother Animal: ")
loc1 = input("\nPlace/Location: ")
adv1 = input("\nAdverb ending in 'ly': ")
emot1 = input("\nPrimary Emotion: ")
print("There once was a/an %s who loved to %s anything the color %s. One day, the %s decided to %s a/an %s it saw walking near %s. Before the %s could do that, however, the %s %s ran away, making the %s become very %s. THE END.", ani1, vb1, col1, ani1, vb2, ani2, loc1, ani1, ani2, adv1, ani1, emot1)
