import time
print("\nHey there!")
time.sleep(1.5)
print("\nGoodbye!")
time.sleep(2)
print("\nHello again!")
time.sleep(1.5)
print("\nFarewell!")
time.sleep(2)
print("\n\n...\n")
time.sleep(2.25)
print("\nI'm back!")
time.sleep(1.5)
print("\nOkay, bye for real!")
time.sleep(2.5)
print("\nPsych! Just kidding!")
time.sleep(1.5)
print("\nI won't come back again-")
time.sleep(1)
print("I promise.")
time.sleep(2.75)
print("\n\nSURPRISE!!!\n")
time.sleep(1.25)
print("\nOkay, I'm done now.")
time.sleep(1.5)
print("\n...")
time.sleep(1.5)
print("\n...")
time.sleep(1.5)
print("\n...\n")
