import time
print("Hey there!")
time.sleep(0.75)
print("Goodbye!")
time.sleep(1)
print("Hello again!")
time.sleep(0.75)
print("Farewell!")
time.sleep(0.875)
print("...")
time.sleep(2)
print("I'm back!")
time.sleep(1)
print("Okay, bye for real!")
time.sleep(2.5)
print("Psych! Just kidding!")
time.sleep(1)
print("I won't come back again-")
time.sleep(1)
print("I promise.")
time.sleep(3.33)
print("SURPRISE!")
time.sleep(1)
print("Okay, I'm done now.")
time.sleep(1.5)
print("...")
time.sleep(1.5)
print("...")
time.sleep(1.5)
print("...")
